name: TestParty Reporter
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TestParty Reporter
        uses: test-party/reporter@v0.0.1-alpha.5
        with:
          testparty_token: d3093553-0d06-404e-83e3-5e8b8c308ecd
          repository_name: ${{ github.repository }}
          repository_id: ${{ github.repository_id }}
          urls: |
              [
                {
                  "url": "https://www.makemytrip.com/flights/sitemap-flights.xml",
                  "steps": []
                },
                {
                  "url": "https://www.makemytrip.com",
                  "steps": []
                }
              ]
          setup: |
            []
          teardown: |
            []
